language: haskell

before_install:
  - cabal install gtk2hs-buildtools hlint
  - travis/cabal-apt-install $mode
  - npm install jshint

install:
  - cabal configure -flib-Werror $mode

script:
  - hlint src
  - jshint --show-non-errors scripts
  - cabal build
  # TODO: tests

env:
  - mode="--enable-tests" script="cabal test --show-details=always"
