language: haskell

ghc:
  - 7.8  # Only used for Cabal

addons:
  apt:
    packages:
      - libwebkitgtk-dev

before_install:
  - wget https://www.stackage.org/stack/linux-x86_64 -O stack.tar.gz
  - tar xf stack.tar.gz
  - mkdir -p $HOME/.local/bin
  - cp stack-*-linux-x86_64/stack $HOME/.local/bin/stack
  - stack setup
  - stack install hlint
  - npm install jshint

install:
  - stack build

script:
  - hlint src
  - jshint --show-non-errors scripts
  # Treat warnings as errors
  - "sed -Ei 's/ghc-options: +/\\0-Werror /' tianbar.cabal"
  - stack test
  # Undo Werror replacement
  - "sed -Ei 's/-Werror //' tianbar.cabal"

cache:
  directories:
    - $HOME/.stack
    - .stack-work

deploy:
  provider: hackage
  username: AlexeyKotlyarov
  password:
    secure: "aVtsJTRT44bUyHEWJEc/Qxa6+HMk+fLq8sNSx/pjHpwivaBjSNVLYQoSo9UHCqU3d7s/vSUhQGCKpg2XzIFh6feUR88OcZH8hnDEgfppCUMMHRr4DOXOStSBBcbjXtNjxmgkqoyJeneaLT9ok5gs5Y0poKdkkngoD4bEEEfbcH0="
  on:
    tags: true
    all_branches: true
    repo: koterpillar/tianbar

sudo: false
