language: haskell

ghc:
  - 7.8
  - 7.6

before_install:
  - cabal install alex gtk2hs-buildtools happy hlint
  - npm install jshint

install:
  - sudo apt-get install libwebkitgtk-dev
  # Treat warnings as errors
  - "sed -Ei 's/ghc-options: +/\0-Werror /' tianbar.cabal"
  - cabal sandbox init
  - cabal install --only-dependencies
  - cabal configure $mode -fWerror

script:
  - hlint src
  - jshint --show-non-errors scripts
  - cabal build
  - cabal test
  - cabal sdist
  - cabal install dist/tianbar*.tar.gz

deploy:
  provider: hackage
  username: AlexeyKotlyarov
  password:
    secure: "aVtsJTRT44bUyHEWJEc/Qxa6+HMk+fLq8sNSx/pjHpwivaBjSNVLYQoSo9UHCqU3d7s/vSUhQGCKpg2XzIFh6feUR88OcZH8hnDEgfppCUMMHRr4DOXOStSBBcbjXtNjxmgkqoyJeneaLT9ok5gs5Y0poKdkkngoD4bEEEfbcH0="
  on:
    tags: true
    all_branches: true
    repo: koterpillar/tianbar
    ghc: 7.8
