packages:
- '.'
- location:
    git: 'git@github.com:koterpillar/gtk-traymanager'
    commit: 7875415bbd0dc161ac9faf13ef89323b09eb022e
  extra-dep: true
extra-deps:
- X11-xft-0.3.1
- gi-javascriptcore-4.0.3
- gi-soup-2.4.3
- gi-webkit2-4.0.3
- xmonad-contrib-0.12
resolver: lts-6.0
