#!/bin/sh -e

DIR=$(dirname $0)

TMP_CONFIG=$(mktemp -d)

trap "rm -rf $TMP_CONFIG" EXIT

LD_PRELOAD=/usr/lib/faketime/libfaketimeMT.so.1 \
FAKETIME='@2014-02-25 11:22:33' \
LC_ALL=C \
XDG_CONFIG_HOME=$TMP_CONFIG \
dbus-launch \
$DIR/../dist/build/tianbar/tianbar &

PID=$!
sleep 5
WINDOW_ID=$(xwininfo -tree -root |
	grep '"tianbar"' |
	head -n 1 |
	awk '{print $1}'
)
xwd -id $WINDOW_ID | convert - PNG:- > $DIR/actual.png
kill $PID

diff -b $DIR/actual.png $DIR/expected.png || (base64 $DIR/actual.png && false)
